name: Build and Push Image


on:
  push:
    branches:
      - main


permissions:
  id-token: write
  contents: read


jobs:

  build:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::665146707658:role/github-actions-ecr-role
        aws-region: eu-north-1


    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2


    - name: Build image
      run: |
        docker build \
        -t mini-server .


    - name: Tag image
      run: |
        docker tag mini-server:${{ github.sha }} \
        665146707658.dkr.ecr.eu-north-1.amazonaws.com/mini-server:${{ github.sha }}


    - name: Push image
      run: |
        docker push \
        665146707658.dkr.ecr.eu-north-1.amazonaws.com/mini-server:${{ github.sha }}

  deploy:

    needs: build

    runs-on: ubuntu-latest


    steps:


    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:

        host: ${{ secrets.EC2_HOST }}

        username: ${{ secrets.EC2_USER }}

        key: ${{ secrets.EC2_SSH_KEY }}

        script: |
          ~/deploy.sh
